{
  "uid" : "de3eecb8854816a1",
  "name" : "test_b",
  "fullName" : "clsp.Test_App5.Test_ABC#test_b",
  "historyId" : "02ec5513fe8c67f3f444c5658bcbbcdc",
  "time" : {
    "start" : 1602663492034,
    "stop" : 1602663492034,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "AssertionError: assert 0",
  "statusTrace" : "self = <Test_App5.Test_ABC object at 0x0471AB10>\n\n    @pytest.mark.xfail(2 > 1, reason=\"标注为预期失败\") # 标记为预期失败函数test_b\n    def test_b(self):\n        print(\"------->test_b\")\n>       assert 0\nE       assert 0\n\nclsp\\Test_App5.py:14: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1602663492029,
      "stop" : 1602663492030,
      "duration" : 1
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1602663492041,
      "stop" : 1602663492041,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(True, reason='标注为预期失败')"
  }, {
    "name" : "parentSuite",
    "value" : "clsp"
  }, {
    "name" : "suite",
    "value" : "Test_App5"
  }, {
    "name" : "subSuite",
    "value" : "Test_ABC"
  }, {
    "name" : "host",
    "value" : "LAPTOP-LFNOOUSC"
  }, {
    "name" : "thread",
    "value" : "15616-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "clsp.Test_App5"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(True, reason='标注为预期失败')" ]
  },
  "source" : "de3eecb8854816a1.json",
  "parameterValues" : [ ]
}