{"name": "test_a[3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 != 3", "trace": "self = <Test_App4.Test_ABC object at 0x0474AB70>, need_data = 3\n\n    def test_a(self,need_data):\n        print(\"------->test_a\")\n>       assert need_data != 3 # 断言need_data不等于3\nE       assert 3 != 3\n\nclsp\\Test_App4.py:11: AssertionError"}, "parameters": [{"name": "need_data", "value": "3"}], "start": 1602663491972, "stop": 1602663491972, "uuid": "60bcb89b-c585-434b-82ae-d90fe1fb3e22", "historyId": "2858af8ec6bf7f8cb45a726abd9eb294", "testCaseId": "251b40918e76e6b755979613dfe98622", "fullName": "clsp.Test_App4.Test_ABC#test_a", "labels": [{"name": "parentSuite", "value": "clsp"}, {"name": "suite", "value": "Test_App4"}, {"name": "subSuite", "value": "Test_ABC"}, {"name": "host", "value": "LAPTOP-LFNOOUSC"}, {"name": "thread", "value": "15616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "clsp.Test_App4"}]}